runtime: nodejs20
entrypoint: node api/index.js

env_variables:
  MONGO_URI: "mongodb+srv://drprakashmptortho:drprakash03@cluster0.dhbjg.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  JWT_SECRET: "alamsfdfsdsdfsdfsdfsdfsdfsdrafdar!@#$0fddlfjdfdfdssfds"
  JWT_SECRET_FOR_VERIFY: "lfjfjasjfsdfsfr09ri09wfsdfsdfrilfdjdj"
  bucketName: "clinicalinventory"

